In [1]:
import numpy as np

In [5]:
arr = np.linspace(1,10,10)
arr

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [7]:
indice_condicion = arr > 5

In [11]:
arr[indice_condicion] # solo imprime los valores True

array([ 6.,  7.,  8.,  9., 10.])

In [13]:
arr[(arr>5) & (arr<8)]

array([6., 7.])

In [14]:
arr[(arr<6)] = 0
arr

array([ 0.,  0.,  0.,  0.,  0.,  6.,  7.,  8.,  9., 10.])

In [15]:
arr[(arr==0)]

array([0., 0., 0., 0., 0.])