In [32]:
import numpy as np

In [33]:
arr = np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [34]:
trozo_de_arr = arr[0:6]
trozo_de_arr

array([0, 1, 2, 3, 4, 5])

In [35]:
trozo_de_arr [:] = 0
trozo_de_arr

array([0, 0, 0, 0, 0, 0])

In [36]:
arr

array([ 0,  0,  0,  0,  0,  0,  6,  7,  8,  9, 10])

In [37]:
# Como evitamos que al cambiar 'trozo_de_arr' se cambie 'arr', ya que se sigue usando el mismo espacio en memoria
# Usamos el comando 'copy', hacemos una copia del 'arr' para usar otro espacio en memoria
arr_copy = arr.copy()
arr_copy

array([ 0,  0,  0,  0,  0,  0,  6,  7,  8,  9, 10])

In [38]:
arr_copy[0:4] = np.arange(0,4)
arr_copy

array([ 0,  1,  2,  3,  0,  0,  6,  7,  8,  9, 10])

In [39]:
print(arr)
print(arr_copy)

[ 0  0  0  0  0  0  6  7  8  9 10]
[ 0  1  2  3  0  0  6  7  8  9 10]
