In [1]:
import numpy as np

In [14]:
list = [i for i in range(0,10)]
print(list)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]


In [16]:
# Crear un array
np.arange(0,10,3) # (numero start, numero stop, step)

array([0, 3, 6, 9])

In [18]:
# Crear un esquema previo al uso (ejemplo, una imagen de 10x5)
np.zeros((10,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [19]:
np.ones((10,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [22]:
# genera un array de números equiespaciados en un intervalo especificado
np.linspace(0,10,10)

array([ 0.        ,  1.11111111,  2.22222222,  3.33333333,  4.44444444,
        5.55555556,  6.66666667,  7.77777778,  8.88888889, 10.        ])

In [23]:
# Matriz con una diagonal del valor dado en '1' y los demas en '0'
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [27]:
# Generar valores aleatorios
np.random.rand()
np.random.rand(4) # genera un array con 4 valores
np.random.rand(4,4) # genera una tupla con 4 valores

array([[0.16231691, 0.38574898, 0.03482004, 0.13886432],
       [0.62055118, 0.24463388, 0.7515278 , 0.05462796],
       [0.24222014, 0.47284957, 0.0788604 , 0.28806069],
       [0.63671195, 0.62711243, 0.26940374, 0.00216098]])

In [46]:
# Genera un valor aleatorio dentro de un rango
np.random.randint(1,15)

6

In [47]:
# Genera un valor aleatorio dentro de un rango, dentro de un esquema dado
np.random.randint(1,15, (10,5))

array([[ 1,  4, 14, 12, 14],
       [13,  6, 11,  2, 14],
       [ 8, 14, 12, 11,  9],
       [ 7, 12,  2,  3, 13],
       [10,  9,  3,  8,  6],
       [ 5, 11,  6,  8,  3],
       [ 2,  5, 14, 13, 14],
       [ 2,  8,  6,  5, 11],
       [13, 14,  6,  1,  2],
       [ 2, 14,  4, 11,  8]], dtype=int32)