In [1]:
import numpy as np

In [3]:
arr = np.random.randint(1,20,10)
print(arr)

[16  2  8  7 10 15  8  1 18 13]


In [4]:
matriz = arr.reshape(2,5)
print(matriz)

[[16  2  8  7 10]
 [15  8  1 18 13]]


In [12]:
print(arr.max()) # El valor maximo del array
print(matriz.max()) # El valor maximo de la matriz
print(matriz.max(0)) # El valor maximo del eje que pedimos
print(matriz.max(1))
# Lo mismo con MIN

18
18
[16  8  8 18 13]
[16 18]


In [15]:
print(arr.argmax()) # El indice donde se encuentra el valor maximo del array
print(matriz.argmax(1))
print(matriz.argmax(0))
# Lo mismo con argMin

8
[0 3]
[0 1 0 1 1]


In [18]:
# pick to pick (diferencia entre el numero mas bajo al numero mas alto)
np.ptp(arr)

np.int32(17)

In [36]:
print(np.ptp(matriz,0)) # distancia entre los numeros por columnas
print(np.ptp(matriz,1)) # distancia entre los numeros por filas

[ 9 11  8  8 10]
[7 8]


In [41]:
# Saber el percentile del array (cual es el valor que se encuentra en el porcentaje que se pida)
np.percentile(arr,30)

np.float64(7.699999999999999)

In [35]:
np.percentile(matriz,50,1)

array([ 7., 15.])

In [28]:
# Ordenar de menor a mayor
arr.sort()
arr

array([ 1,  2,  7,  8,  8, 10, 13, 15, 16, 18], dtype=int32)

In [30]:
matriz.sort()
matriz

array([[ 1,  2,  7,  8,  8],
       [10, 13, 15, 16, 18]], dtype=int32)

In [29]:
# Saber la mediana del array o matriz, esto es igual al percentil 50
np.median(arr)

np.float64(9.0)

In [34]:
np.median(matriz,1)

array([ 7., 15.])

In [40]:
# Saber la desviacion estandar
np.std(arr)

np.float64(5.436910887627275)

In [38]:
# Saber la vairnaza
np.var(arr)

np.float64(29.560000000000002)

In [42]:
# Saber la media del array o matriz
np.mean(arr)

np.float64(9.8)

Concatenar

In [44]:
a = np.array([[1,2],[3,4]])
b = np.array([5,6])

In [48]:
# Hay un error, no se pueden unir al ser de diferentes dimensiones, las tenemos que poner igual
b = np.expand_dims(b,axis=0)

In [49]:
np.concatenate((a,b), axis=0)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [51]:
np.concatenate((a,b), axis=1)

ValueError: all the input array dimensions except for the concatenation axis must match exactly, but along dimension 0, the array at index 0 has size 2 and the array at index 1 has size 1

In [52]:
# Hay un error, tenemosque cambiarla de forma para poder unir de forma columnas
np.concatenate((a,b.T), axis=1) # La T es la transpuesta, es simplemente cmabiarle la forma

array([[1, 2, 5],
       [3, 4, 6]])