In [1]:
import numpy as np

In [2]:
lista = [1,2,3,4,5,6,7,8,9]
lista

[1, 2, 3, 4, 5, 6, 7, 8, 9]

In [5]:
arr = np.array(lista)
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
type(arr)

numpy.ndarray

In [8]:
matriz = [[1,2,3],[4,5,6],[7,8,9]]
arrMatriz = np.array(matriz)
arrMatriz

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [13]:
# indexing (acceder a valores del array por el index)
print(arr[5])
print(arrMatriz[0]) # Accede al primero a las filas, en este caso la fila 0
print(arrMatriz[0,2]) # Accede a un numero en especifico, [filas, columnas]

6
[1 2 3]
3


In [19]:
# slicing (acceder a un conjunto de valores)
print(arr[0:3]) # de la posicion 0 a la posicion 3
print(arr[:6]) # si no se pone el primer numero, arranca desde el 0 hasta el index puesto
print(arr[2:]) # si no se pone el segundo numero, arranca desde el index puesto hasta el final
print(arr[::3]) # el ultimo numero son los brincos que hace de index (en este caso, de 3 en 3)
print(arr[-1]) # un 'menos' lo hace alreves (empieza desde el final)

[1 2 3]
[1 2 3 4 5 6]
[3 4 5 6 7 8 9]
[1 4 7]
9


In [22]:
# slicing en matriz
print(arrMatriz[1:]) # imprime de la fila uno en adelante
print(arrMatriz[1:, 0:2]) # imprime de la fila uno en adelante, de la columna 0 a la 2

[[4 5 6]
 [7 8 9]]
[[4 5]
 [7 8]]
