In [17]:
import numpy as np

In [18]:
lista = [1,2]
lista

[1, 2]

In [19]:
lista * 2

[1, 2, 1, 2]

In [20]:
arr = np.arange(0,10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [21]:
arr2 = arr.copy()

Operaciones

In [22]:
arr + 2

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [23]:
arr * 2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [24]:
arr / 1

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [25]:
arr + arr2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [26]:
arr * arr2

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [27]:
arr / arr2

C:\Users\tamez\AppData\Local\Temp\ipykernel_21192\1444868932.py:1: RuntimeWarning: invalid value encountered in divide
  arr / arr2


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [29]:
matriz = arr.reshape(2,5)
matriz

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [30]:
matriz2 = matriz.copy()

In [31]:
matriz + matriz2

array([[ 0,  2,  4,  6,  8],
       [10, 12, 14, 16, 18]])

In [33]:
np.matmul(matriz,matriz2.T)

array([[ 30,  80],
       [ 80, 255]])

In [34]:
matriz@matriz2.T

array([[ 30,  80],
       [ 80, 255]])