In [1]:
import numpy as np

In [4]:
arr = np.random.randint(1,10,(3,2))
print(arr)

[[6 4]
 [8 8]
 [6 7]]


In [3]:
arr.shape

(3, 2)

In [5]:
# Cambiar la forma del array, y los valores se ajustan solo a la nueva forma
arr.reshape(1,6)

array([[6, 4, 8, 8, 6, 7]], dtype=int32)

In [6]:
arr.reshape(2,3)

array([[6, 4, 8],
       [8, 6, 7]], dtype=int32)

In [9]:
np.reshape(arr,(6,1))

array([[6],
       [4],
       [8],
       [8],
       [6],
       [7]], dtype=int32)

In [10]:
print(arr)

[[6 4]
 [8 8]
 [6 7]]


In [11]:
# Saber como se acomodan los valores en base al lenguaje C
np.reshape(arr,(2,3),'C') # Los toma por filas

array([[6, 4, 8],
       [8, 6, 7]], dtype=int32)

In [12]:
# Saber como se acomodan los valores en base al lenguaje Fortran
np.reshape(arr,(2,3),'F') # Los toma por columnas

array([[6, 6, 8],
       [8, 4, 7]], dtype=int32)

In [13]:
# Saber como se acomodan los valores en base a la mejor optimizacion y el guardado de datos en el sistema
np.reshape(arr,(2,3),'A') # Toma la desicion si lo hace en base a C o F

array([[6, 4, 8],
       [8, 6, 7]], dtype=int32)