In [12]:
import numpy as np

In [23]:
arr = np.array([0,1,2,3,4])
print(arr)
arr.dtype

[0 1 2 3 4]


dtype('int64')

In [24]:
# se cambia la propiedad despues de inicilar la lista a float
arr = arr.astype(np.float64)

In [25]:
print(arr)

[0. 1. 2. 3. 4.]


In [26]:
# lo cambiamos a boleano
arr = arr.astype(np.bool_)
print(arr)
arr.dtype

[False  True  True  True  True]


dtype('bool')

In [33]:
arr = np.array([0,1,2,3,4])
arr = arr.astype(np.bytes_)
print(arr)
arr.dtype

[b'0' b'1' b'2' b'3' b'4']


dtype('S21')

In [34]:
arr = arr.astype(np.int8)
print(arr)
arr.dtype

[0 1 2 3 4]


dtype('int8')